name: Window create executable python

on: [push]

jobs:
  build-linux:
    runs-on: windows-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Start all
      run: |
        cd releases
        client
